// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AIMS.Server.Models;

public partial class FarmRecords
{
    public int Id { get; set; }

    public int? CropId { get; set; }

    public string Action { get; set; }

    public DateTime? RecordDate { get; set; }

    public string Description { get; set; }

    public virtual Crops Crop { get; set; }
}