// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AIMS.Server.Models;

public partial class Users
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Role { get; set; }

    public string RealName { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<Crops> Crops { get; set; } = new List<Crops>();
}